- name: Terminate ec2 instance
  hosts: localhost
  gather_facts: yes
  pre_tasks:
    - name: read instance id
      command: "redis-cli lindex box3 0"
      register: redis_instance_id
    - name: read instance region
      command: "redis-cli lindex box3 2"
      register: redis_instance_region
    - name: set instance facts
      set_fact:
        instance_id:     "{{ redis_instance_id.stdout }}"
        instance_region: "{{ redis_instance_region.stdout }}"
        instance_name       :  "{{ lookup('env', 'instance_name') }}"
  tasks:
    - name: Terminate the instance
      local_action:
        module: ec2
        state: 'absent'
        region: "{{ instance_region }}"
        instance_ids: '{{ instance_id }}'

    - name: remove from ssh config
      blockinfile:
        path: '/home/sandbox/.ssh/config'
        create: yes
        marker: "## {mark} intsnace {{ instance_name }}"
        block: |
          
    - name: remove ansible inventory
      blockinfile:
        path: '/home/sandbox/env_variables/inventory'
        create: yes
        marker: "## {mark} intsnace {{ instance_name }}"
        block: |
          
  

